### ISSUE TITLE
How good is this without Nitro card support

### ISSUE THREAD

**Issue by marsupialtail** [aws/libfabric#8]
To the best of my knowledge, libfabric allows some EC2 instances with the letter n in their name to interface efficiently with AWS Nitro cards implementing the SRD protocol. 

I am wondering -- assuming that I do not have the hardware support an implement the SRD in software, could I still expect a speedup in my communications compared to TCP. 

Any general comments would be appreciated.

**Comment by rhiswell** [comment]
Like TCP, the transport provides message passing semantics in datacenter should implements six features, connection management,  including large message segmentation and assembly, message ordering, loss recovery, multi-path delivery and congestion control. SRD-based ULP can achieve better performance because it offloads the later three features, through SRD doesn't eliminate data copy at end host. If you implement SRD in software, I doubt there still a good performance improvement.

**Comment by a-szegel** [comment]
This repository is used when AWS needs to deploy a bugfix in libfabric (on AWS), before the libfabric community is ready to release.  Hence, this repository is not actively monitored.  All active development activity happens here: https://github.com/ofiwg/libfabric. The libfabric project supplies an interface for applications/libraries that need optimized networking beyond what TCP/IP can do.  If you are interested in learning more, please read https://github.com/ofiwg/ofi-guide/blob/master/OFIGuide.md.
